allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  sharp: true
minimumReleaseAgeExclude:
  - '@firecrawl/anydoc-darwin-arm64@0.1.7'
  - '@firecrawl/anydoc-darwin-x64@0.1.7'
  - '@firecrawl/anydoc-linux-arm64-gnu@0.1.7'
  - '@firecrawl/anydoc-linux-arm64-musl@0.1.7'
  - '@firecrawl/anydoc-linux-x64-gnu@0.1.7'
  - '@firecrawl/anydoc-linux-x64-musl@0.1.7'
  - '@firecrawl/anydoc-win32-x64-msvc@0.1.7'
  - '@firecrawl/anydoc@0.1.7'
