"use client";
import {useRef,useState} from "react";
import {authClient} from "../../../lib/auth-client";
import {WaitlistModal} from "../../components/waitlist-modal";
type SourceType="resume"|"linkedin"|"github";type Source={type:SourceType;label:string;url:string|null;syncedAt:string|null;data?:unknown};
function fieldLabel(value:string){return value.replace(/([a-z])([A-Z])/g,"$1 $2").replace(/_/g," ").replace(/^./,letter=>letter.toUpperCase())}
function DataValue({value}:{value:unknown}){if(value==null||value==="")return <span className="text-subtle">Not provided</span>;if(typeof value==="string")return <p className="whitespace-pre-wrap wrap-break-word text-body-s leading-relaxed text-muted">{value}</p>;if(typeof value==="number"||typeof value==="boolean")return <span className="text-body-s text-muted">{String(value)}</span>;if(Array.isArray(value))return value.length?<div className="space-y-2">{value.map((item,index)=><div className="rounded-control border border-ui-border-subtle bg-page-subtle p-3" key={index}><DataValue value={item}/></div>)}</div>:<span className="text-subtle">None found</span>;if(typeof value==="object")return <dl className="space-y-3">{Object.entries(value as Record<string,unknown>).map(([key,item])=><div className="border-b border-ui-border-subtle pb-3 last:border-0 last:pb-0" key={key}><dt className="mb-1 text-label font-semibold uppercase tracking-wide text-subtle">{fieldLabel(key)}</dt><dd><DataValue value={item}/></dd></div>)}</dl>;return null}
function EvidenceModal({source,onClose}:{source:Source;onClose:()=>void}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-(--color-scrim) p-4 backdrop-blur-[2px]" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section aria-modal="true" role="dialog" className="flex max-h-[90vh] w-full max-w-180 flex-col rounded-card border border-ui-border-subtle bg-ui-surface shadow-(--shadow-lift)"><header className="flex items-start justify-between gap-4 border-b border-ui-border-subtle p-5 sm:p-6"><div><p className="kicker text-accent">Retrieved evidence</p><h2 className="mt-2 font-display text-display-s font-bold">{source.label}</h2><p className="mt-1 text-body-s text-muted">The information Lenni uses for profile, job, and roadmap analysis.</p></div><button aria-label="Close" className="flex size-8 shrink-0 items-center justify-center rounded-full text-subtle hover:bg-ui-raised" onClick={onClose}>✕</button></header><div className="min-h-0 flex-1 overflow-y-auto p-5 sm:p-6"><DataValue value={source.data}/></div></section></div>}
export function SourceActions({released,githubConnected,initialSources}:{released:boolean;githubConnected:boolean;initialSources:Source[]}){
 const[sources,setSources]=useState(initialSources);const[waitlist,setWaitlist]=useState(false);const[busy,setBusy]=useState<SourceType|null>(null);const[message,setMessage]=useState("");const[viewing,setViewing]=useState<Source|null>(null);const resumeRef=useRef<HTMLInputElement>(null);const linkedInRef=useRef<HTMLInputElement>(null);
 function gate(action:()=>void){if(!released){setWaitlist(true);return}action()}
 function sourceFor(type:SourceType){return [...sources].reverse().find(source=>source.type===type)}
 async function connectGithub(){if(!githubConnected){await authClient.signIn.social({provider:"github",callbackURL:"/profile?github=connected"});return}setBusy("github");setMessage("");const response=await fetch("/api/profile/github",{method:"POST"});const data=await response.json();setBusy(null);if(!response.ok){setMessage(data.error??"GitHub sync failed");return}setSources(current=>[...current.filter(source=>source.type!=="github"),{type:"github",label:"GitHub",url:data.source.externalUrl,syncedAt:data.source.syncedAt,data:data.source.parsedData}]);setMessage(`${data.repositoryCount} GitHub repositories added to your profile evidence.`)}
 async function upload(type:"resume"|"linkedin",file:File){setBusy(type);setMessage("");const body=new FormData();body.set("file",file);const response=await fetch(`/api/profile/${type}`,{method:"POST",body});const data=await response.json();setBusy(null);if(!response.ok){setMessage(data.error??`Unable to analyze ${type}.`);return}const label=type==="resume"?(data.source.fileName??"Résumé"):"LinkedIn";setSources(current=>[...current.filter(source=>source.type!==type),{type,label,url:data.source.externalUrl??null,syncedAt:data.source.syncedAt,data:data.source.parsedData}]);setMessage(`${label} updated. ${data.analysis.skills.length} skills found.`)}
 const cards:[SourceType,string][]=[["resume",sourceFor("resume")?.label??"Résumé"],["linkedin","LinkedIn"],["github","GitHub"]];
 function action(type:SourceType,exists:boolean){if(type==="github")return gate(connectGithub);gate(()=>{(type==="resume"?resumeRef:linkedInRef).current?.click()})}
 return <><section className="mt-6 card p-6"><div><h2 className="font-display text-display-s font-bold">Profile evidence</h2><p className="mt-1 text-body-s text-muted">Lenni uses these sources to make job matches and roadmap updates specific to you.</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{cards.map(([type,fallback])=>{const source=sourceFor(type);const loading=busy===type;return <article className={`flex items-center justify-between gap-4 rounded-control border p-4 ${source?"border-positive-subtle bg-positive-subtle":"border-ui-border-subtle bg-page-subtle"}`} key={type}><div className="min-w-0">{source?.url?<a className="font-semibold text-positive hover:underline" href={source.url} rel="noreferrer" target="_blank">✓ {source.label}</a>:<p className={`font-semibold ${source?"text-positive":"text-foreground"}`}>{source?"✓ ":""}{source?.label??fallback}</p>}<p className={`mt-1 text-label ${source?"text-positive opacity-80":"text-muted"}`}>{source?"Ready for analysis":"Not analyzed yet"}</p></div><div className="flex shrink-0 flex-col gap-2 sm:flex-row">{source&&<button className="btn btn-ghost btn-sm" onClick={()=>setViewing(source)}>View data</button>}<button className="btn btn-secondary btn-sm" disabled={busy!==null} onClick={()=>action(type,Boolean(source))}>{loading?(type==="github"?"Syncing…":"Analyzing…"):source?"Update":type==="github"?"Connect":"Analyze"}</button></div></article>})}</div><input ref={resumeRef} className="hidden" type="file" accept=".pdf,.doc,.docx,.docm,.odt,.rtf" onChange={event=>{const file=event.target.files?.[0];if(file)upload("resume",file);event.target.value=""}}/><input ref={linkedInRef} className="hidden" type="file" accept="application/pdf,.pdf" onChange={event=>{const file=event.target.files?.[0];if(file)upload("linkedin",file);event.target.value=""}}/>{message&&<p className="mt-4 rounded-control bg-page-subtle p-3 text-body-s text-muted">{message}</p>}</section>{viewing&&<EvidenceModal source={viewing} onClose={()=>setViewing(null)}/>}<WaitlistModal open={waitlist} onClose={()=>setWaitlist(false)} source="profile-sources"/></>;
}
