"use client";
import Link from "next/link";
import { useState } from "react";
import { RoleIcon, roleIconColors } from "../../components/role-icon";
import { useAuthProgress } from "../auth-progress";

type Gap = { name: string; missing: boolean };
const careers = [
  { slug: "ai-engineer", title: "AI Engineer", description: "Python → ML → LLM systems → production", icon: "network" as const, color: "blue" as const },
  { slug: "bitcoin-developer", title: "Bitcoin Developer", description: "Bitcoin Core → wallets → Lightning → open source", icon: "server" as const, color: "amber" as const },
];
export default function OnboardingPage() {
  const [resume,setResume]=useState<File|null>(null); const [step,setStep]=useState<2|3|4>(2); const [career,setCareer]=useState(careers[0]); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [skills,setSkills]=useState<Gap[]>([]);
  useAuthProgress(step);
  const card="rounded-xl border border-ui-border-subtle bg-ui-surface p-8 shadow-(--shadow) max-[400px]:p-6";
  const button="inline-flex cursor-pointer items-center justify-center rounded-2xl border-2 px-6 py-3.25 text-[13.5px] font-extrabold uppercase disabled:opacity-45";
  async function analyze(){if(!resume)return;setStep(4);setLoading(true);setError("");const data=new FormData();data.set("resume",resume);data.set("career",career.slug);const response=await fetch("/api/onboarding",{method:"POST",body:data});const body=await response.json();setLoading(false);if(!response.ok){setError(body.error??"Analysis failed");return;}setSkills(body.skills);}
  if(step===2)return <section className={card}><h1 className="mb-2 font-display text-[23px] font-semibold">Import your profile</h1><p className="mb-6.5 text-sm text-muted">Upload your résumé so Lenni can retrieve demonstrated experience.</p><label className={`flex cursor-pointer items-center gap-3 rounded-xl border-[1.5px] p-4 ${resume?"border-positive bg-positive-subtle":"border-dashed border-ui-border"}`}><span className="flex-1"><strong className="block text-sm">{resume?.name??"Upload résumé"}</strong><span className="text-xs text-subtle">PDF or DOCX, up to 10MB</span></span><input className="sr-only" type="file" accept=".pdf,.doc,.docx" onChange={e=>setResume(e.target.files?.[0]??null)}/></label><button className={`${button} mt-6 w-full border-accent bg-accent text-white`} disabled={!resume} onClick={()=>setStep(3)}>Continue</button></section>;
  if(step===3)return <section className={card}><h1 className="mb-2 font-display text-[23px] font-semibold">Choose your goal</h1><p className="mb-6 text-sm text-muted">Choose the career path Lenni should build around your current experience.</p><div className="grid grid-cols-2 gap-3 max-[430px]:grid-cols-1">{careers.map(item=><button key={item.slug} onClick={()=>setCareer(item)} className={`rounded-xl border p-4 text-left transition ${career.slug===item.slug?"border-accent bg-accent-subtle":"border-ui-border bg-page-subtle hover:border-subtle"}`}><span className={`mb-4 flex size-11 items-center justify-center rounded-xl ${roleIconColors[item.color]}`}><RoleIcon name={item.icon}/></span><strong>{item.title}</strong><p className="mt-1 text-xs text-muted">{item.description}</p></button>)}</div><div className="mt-6 flex justify-between"><button className={`${button} border-ui-border`} onClick={()=>setStep(2)}>Back</button><button className={`${button} border-accent bg-accent text-white`} onClick={analyze}>Analyze profile</button></div></section>;
  return <section className={card}>{loading?<div className="py-8 text-center"><span className="mx-auto mb-5 block size-4 animate-pulse rounded-full bg-accent"/><h1 className="font-display text-[23px] font-semibold">Mapping your {career.title} path</h1><p className="mt-2 text-sm text-muted">Extracting evidence, comparing the benchmark, and generating lessons…</p></div>:error?<div><h1 className="font-display text-xl font-semibold">Analysis couldn’t finish</h1><p className="my-4 rounded-lg bg-negative-subtle p-3 text-sm text-negative">{error}</p><button className={`${button} border-ui-border`} onClick={()=>setStep(2)}>Try again</button></div>:<div><h1 className="mb-2 font-display text-[23px] font-semibold">Here’s your starting point</h1><p className="mb-5 text-sm text-muted">Your personalized {career.title} roadmap has been created.</p>{skills.slice(0,10).map(skill=><div className="flex justify-between border-b border-ui-border-subtle py-2.5 text-sm" key={skill.name}><span>{skill.name}</span><span className={`rounded-md px-2 py-1 text-xs ${skill.missing?"bg-negative-subtle text-negative":"bg-positive-subtle text-positive"}`}>{skill.missing?"Gap":"Evidence found"}</span></div>)}<Link className={`${button} mt-6 w-full border-accent bg-accent text-white`} href="/dashboard">Open my roadmap →</Link></div>}</section>;
}
