import {NextResponse} from "next/server";
import {z} from "zod";
import {generateJson} from "../../../../lib/ai";
import {careerPrompt} from "../../../../lib/prompts";
import {prisma} from "../../../../lib/prisma";
import {apiUser} from "../../../../lib/session";
import {featuresReleased,releaseUnavailable} from "../../../../lib/release";
const schema=z.object({title:z.string(),company:z.string().nullable().default(null),location:z.string().nullable().default(null),score:z.number().min(0).max(100),summary:z.string(),requiredSkills:z.array(z.string()),preferredSkills:z.array(z.string()),matchedSkills:z.array(z.string()),missingSkills:z.array(z.string()),strengths:z.array(z.string()),gaps:z.array(z.string()),actions:z.array(z.string()),explanation:z.string()});
export async function POST(request:Request){const user=await apiUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});if(!featuresReleased())return NextResponse.json(releaseUnavailable,{status:403});try{const {description}=z.object({description:z.string().min(100).max(30000)}).parse(await request.json());const [goal,profile,sources,rows]=await Promise.all([prisma.careerGoal.findFirst({where:{userId:user.id,isActive:true}}),prisma.profile.findUnique({where:{userId:user.id}}),prisma.profileSource.findMany({where:{userId:user.id,status:"ready"},select:{type:true,parsedData:true}}),prisma.userSkill.findMany({where:{userId:user.id}})]);const role=goal?.roleId?await prisma.role.findUnique({where:{id:goal.roleId}}):null;const selectedCareer=careerPrompt(role?.slug);const skills=rows.length?await prisma.skill.findMany({where:{id:{in:rows.map(row=>row.skillId)}}}):[];const names=new Map(skills.map(skill=>[skill.id,skill.name]));const skillProfile=rows.map(row=>({name:names.get(row.skillId),score:Number(row.score),confidence:Number(row.confidence)}));const output=schema.parse(await generateJson(user.id,"job_evaluation",`${selectedCareer.jobEvaluation}\nUse profile fields, analyzed LinkedIn evidence, and GitHub repository evidence when available. Never invent experience. Return {title,company,location,score,summary,requiredSkills,preferredSkills,matchedSkills,missingSkills,strengths,gaps,actions,explanation}. Strengths and gaps must cite specific supplied evidence; actions must be practical before applying.`,{career:selectedCareer.title,description,profile,skills:skillProfile,sources}));const saved=await prisma.jobEvaluation.create({data:{userId:user.id,rawDescription:description,detectedTitle:output.title,company:output.company,location:output.location,score:output.score,matchedSkills:output.matchedSkills,missingSkills:output.missingSkills,preferredSkills:output.preferredSkills,strengths:output.strengths,gaps:output.gaps,actions:output.actions,summary:output.summary}});return NextResponse.json({...output,id:saved.id,createdAt:saved.createdAt});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Evaluation failed"},{status:400});}}
