"use client";
import Link from "next/link";
import { useState } from "react";

const card="rounded-xl border border-ui-border-subtle bg-ui-surface p-6 shadow-(--shadow)";
export default function DashboardPage(){
 const [done,setDone]=useState([true,false,false]);
 const todos=[["Review yesterday’s lesson — Backpropagation","10 min"],["Complete today’s lesson — Loss Functions","20 min"],["Finish one exercise","15 min"]];
 return <><div className="mb-7 flex flex-wrap items-start justify-between gap-3.5"><div><p className="mb-2.5 font-mono text-[11px] font-medium uppercase tracking-[.14em] text-accent">Friday, July 31</p><h1 className="font-display text-[32px] font-semibold tracking-[-.01em]">Good afternoon, Maya</h1></div><div className="flex items-center gap-2 rounded-full border border-ui-border-subtle bg-ui-surface px-4 py-2.25 font-mono text-[13px]"><span className="text-caution">◆</span><span>12 day streak</span></div></div>
 <div className="mb-4.5 grid grid-cols-[1.5fr_1fr] gap-4.5 max-[900px]:grid-cols-1"><article className={`${card} overflow-hidden`}><p className="mb-2.5 font-mono text-[11px] uppercase tracking-[.14em] text-accent">Career goal</p><h2 className="mb-4.5 font-display text-[26px] font-semibold">Become AI Engineer</h2><div className="flex items-center gap-5"><div className="relative size-22 shrink-0"><svg className="size-full -rotate-90" viewBox="0 0 88 88"><circle cx="44" cy="44" r="38" fill="none" stroke="var(--color-border)" strokeWidth="7"/><circle cx="44" cy="44" r="38" fill="none" stroke="var(--color-brand)" strokeWidth="7" strokeLinecap="round" strokeDasharray="238.8" strokeDashoffset="93"/></svg><span className="absolute inset-0 flex items-center justify-center font-mono text-lg font-semibold">61%</span></div><div><p className="text-xs text-subtle">Current milestone</p><p className="mt-0.75 text-[14.5px] font-semibold">Machine Learning Foundations</p><p className="mt-2.5 text-xs text-subtle">Modules left</p><p className="mt-0.75 text-[14.5px] font-semibold">4 of 7</p></div></div><div className="mt-5 border-t border-ui-border-subtle pt-4.5"><p className="mb-2.5 font-mono text-[11.5px] uppercase tracking-[.08em] text-subtle">Path so far</p><svg viewBox="0 0 460 46" className="h-11.5 w-full"><path d="M6 30 C60 6 90 46 150 24 S240 4 300 26 S400 8 454 20" fill="none" stroke="var(--color-border)" strokeWidth="2" strokeDasharray="1 8"/><path d="M6 30 C60 6 90 46 150 24 S220 10 255 20" fill="none" stroke="var(--color-success)" strokeWidth="2.5"/><circle cx="6" cy="30" r="5" fill="var(--color-success)"/><circle cx="90" cy="46" r="4.5" fill="var(--color-success)"/><circle cx="150" cy="24" r="4.5" fill="var(--color-success)"/><circle cx="255" cy="20" r="6" fill="var(--color-brand)" stroke="white" strokeWidth="2"/><circle cx="300" cy="26" r="4.5" fill="#c7ccd6"/><circle cx="378" cy="12" r="4.5" fill="#c7ccd6"/><circle cx="454" cy="20" r="4.5" fill="#c7ccd6"/></svg></div></article>
 <article className={`${card} flex flex-col gap-3.5`}><div className="flex items-center gap-2.5"><span className="flex size-7 items-center justify-center rounded-lg bg-accent-subtle text-accent">◇</span><span className="text-[12.5px] font-semibold text-muted">AI Coach</span></div><p className="text-sm leading-normal">Nice work — <strong className="font-semibold text-accent">3 lessons this week</strong>. Today continues straight from where Deep Learning left off, so no context to re-load.</p><Link className="mt-auto rounded-2xl border-2 border-ui-border bg-white px-6 py-3.25 text-center text-[13.5px] font-extrabold uppercase tracking-[.03em] text-muted shadow-[0_4px_0_var(--color-border)]" href="/progress">See weekly summary</Link></article></div>
 <article className={card}><p className="mb-2.5 font-mono text-[11px] uppercase tracking-[.14em] text-accent">Today’s plan · 45 min</p><div>{todos.map(([text,time],i)=><button className="flex w-full items-center gap-3 rounded-lg px-2.5 py-3 text-left transition hover:bg-accent-subtle" onClick={()=>setDone(v=>v.map((x,j)=>j===i?!x:x))} key={text}><span className={`flex size-5 shrink-0 items-center justify-center rounded-md border-[1.5px] ${done[i]?"border-positive bg-positive text-white":"border-ui-border"}`}>{done[i]?"✓":""}</span><span className={`flex-1 text-sm ${done[i]?"text-subtle line-through":""}`}>{text}</span><span className="font-mono text-[11.5px] text-subtle">{time}</span></button>)}</div></article>
 <div className="mt-6 flex items-center justify-between rounded-xl border border-ui-border-subtle bg-gradient-to-br from-accent-subtle to-ui-surface px-6.5 py-5.5"><div><p className="mb-1 font-mono text-[11px] uppercase tracking-[.08em] text-subtle">Continue where you left off</p><h3 className="font-display text-[19px] font-semibold">Loss Functions</h3></div><Link className="rounded-2xl border-2 border-accent bg-accent px-6 py-3.25 text-[13.5px] font-extrabold uppercase tracking-[.03em] text-white shadow-[0_4px_0_var(--color-brand-strong)]" href="/lesson">Continue learning →</Link></div></>;
}
