import Link from "next/link";
import {notFound} from "next/navigation";
import {prisma} from "../../../../lib/prisma";
import {getSession} from "../../../../lib/session";
import {matchMockJob,mockJobs} from "../../../../lib/mock-jobs";
import {AddGapsButton} from "./add-gaps-button";

function strings(value:unknown){return Array.isArray(value)?value.filter((item):item is string=>typeof item==="string"):[]}
function Section({title,items,tone="neutral"}:{title:string;items:string[];tone?:"positive"|"negative"|"neutral"}){const color=tone==="positive"?"bg-positive-subtle text-positive":tone==="negative"?"bg-negative-subtle text-negative":"bg-page-subtle text-muted";return <section className="card p-6"><h2 className="font-display text-display-s font-bold">{title}</h2><ul className="mt-4 space-y-3">{items.map(item=><li className={`rounded-control p-3 text-body ${color}`} key={item}>{item}</li>)}</ul></section>}

export default async function JobAnalysisPage({params}:{params:Promise<{id:string}>}){
 const session=await getSession();const{id}=await params;
 const mockJob=mockJobs.find(item=>item.id===id);
 const saved=mockJob?null:await prisma.jobEvaluation.findFirst({where:{id,userId:session!.user.id}});
 let job:{id:string;title:string;company:string|null;location:string|null;score:number;summary:string;required:string[];preferred:string[];strengths:string[];gaps:string[];actions:string[];rawDescription:string;alreadyAdded:boolean};
 if(saved){job={id:saved.id,title:saved.detectedTitle??"Evaluated role",company:saved.company,location:saved.location,score:Math.round(Number(saved.score)),summary:saved.summary??"Lenni compared this posting with your current profile evidence.",required:[...strings(saved.matchedSkills),...strings(saved.missingSkills)],preferred:strings(saved.preferredSkills),strengths:strings(saved.strengths),gaps:strings(saved.gaps).length?strings(saved.gaps):strings(saved.missingSkills),actions:strings(saved.actions),rawDescription:saved.rawDescription,alreadyAdded:Boolean(saved.addedToRoadmapAt)}}else{
  const mock=mockJob;if(!mock)notFound();
  const rows=await prisma.userSkill.findMany({where:{userId:session!.user.id}});const records=rows.length?await prisma.skill.findMany({where:{id:{in:rows.map(row=>row.skillId)}}}):[];const names=new Map(records.map(skill=>[skill.id,skill]));const profileSkills=rows.flatMap(row=>{const skill=names.get(row.skillId);return skill?[{name:skill.name,slug:skill.slug,score:Number(row.score)}]:[]});const match=matchMockJob(mock,profileSkills);const required=mock.requirements.map(item=>item.label);const strengths=required.filter(item=>!match.gaps.includes(item));job={id:mock.id,title:mock.title,company:mock.company,location:null,score:match.match,summary:`This role emphasizes ${required.join(", ")}. Lenni compared those requirements with your currently tracked skills.`,required,preferred:[],strengths:strengths.length?strengths.map(item=>`Your profile shows relevant evidence for ${item}.`):["No requirement has strong enough evidence yet."],gaps:match.gaps,actions:match.gaps.map(item=>`Build or document a project that demonstrates ${item}.`),rawDescription:`${mock.title} at ${mock.company}\n\nCore requirements: ${required.join(", ")}.`,alreadyAdded:false};
 }
 const verdict=job.score>=75?"Strong match":job.score>=50?"Promising with focused gaps":"Longer-term opportunity";
 return <><Link className="text-body-s text-muted hover:text-foreground" href="/jobs">← Back to jobs</Link><header className="mt-5 flex flex-wrap items-end justify-between gap-5"><div><p className="kicker text-accent">Job analysis</p><h1 className="mt-2 font-display text-display-m md:text-display-l font-bold">{job.title}</h1><p className="mt-1 text-body text-muted">{[job.company,job.location].filter(Boolean).join(" · ")||"Profile-aware fit review"}</p></div><div className="rounded-card border border-ui-border bg-ui-surface px-6 py-4 text-center"><strong className="font-display text-display-m">{job.score}%</strong><span className="block text-label text-muted">profile match</span></div></header><section className="card mt-6 flex flex-col gap-5 p-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="kicker text-accent">{verdict}</p><h2 className="mt-2 font-display text-display-s font-bold">How Lenni reached this score</h2><p className="mt-2 max-w-170 text-body leading-relaxed text-muted">The score compares the role’s requirements with evidence from your profile, analyzed documents, tracked skills, and connected GitHub work.</p></div><AddGapsButton jobId={job.id} alreadyAdded={job.alreadyAdded}/></section><section className="card mt-6 p-6"><h2 className="font-display text-display-s font-bold">What this role needs</h2><p className="mt-3 text-body leading-relaxed text-muted">{job.summary}</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><div><h3 className="font-semibold">Required</h3><div className="mt-2 flex flex-wrap gap-2">{job.required.map(skill=><span className="rounded-chip bg-page-subtle px-3 py-1 text-label" key={skill}>{skill}</span>)}</div></div><div><h3 className="font-semibold">Preferred</h3><div className="mt-2 flex flex-wrap gap-2">{job.preferred.length?job.preferred.map(skill=><span className="rounded-chip bg-page-subtle px-3 py-1 text-label" key={skill}>{skill}</span>):<span className="text-body-s text-subtle">None identified</span>}</div></div></div></section><div className="mt-5 grid gap-5 lg:grid-cols-2"><Section title="Evidence in your favor" items={job.strengths} tone="positive"/><Section title="Gaps to address" items={job.gaps} tone="negative"/></div><div className="mt-5"><Section title="Before you apply" items={job.actions}/></div><details className="card mt-5 p-6"><summary className="cursor-pointer font-display text-body-l font-bold">Original job description</summary><p className="mt-4 whitespace-pre-wrap text-body-s leading-relaxed text-muted">{job.rawDescription}</p></details></>;
}
